### PR TITLE
PMM-9749 Change data type from int to string in column value in PGSM settings.

### PR DESCRIPTION
**Pull request by JiriCtvrtka**
PMM-9749

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

### CODE REVIEW

**Comment by percona-csalguero** [comment]
Do we need a migration for this change?

**Review by percona-csalguero — COMMENTED** [review]
Do we need a migration for this change?

**Comment by JiriCtvrtka** [comment]
@percona-csalguero No it is change on PGSM side. In theirs settings.

**Review by ShashankSinha252 — APPROVED** [review]
LGTM

**Review by percona-csalguero — APPROVED** [review]

**Pull request merged**
