### PR TITLE
Add PR template

### PR DESCRIPTION
**Pull request by artemgavrilov**
PMM-0

Build: SUBMODULES-1

- [ ] Links to other linked pull requests (optional).

### CODE REVIEW

**Comment by artemgavrilov** [comment]
@nikita-b can you please enable autolinks in this repo, same as we have in pmm-managed

**Comment by artemgavrilov** [comment]
Build: SUBMODULES-1

**Comment by idoqo** [comment]
PMM-0

**Comment by idoqo** [comment]
> [PMM-0](https://jira.percona.com/browse/PMM-0)

So this works because autolinks are enabled now. Got it.

**Review by idoqo — APPROVED** [review]

**Review by PavelKhripkov — APPROVED** [review]

**Pull request merged**
