### PR TITLE
PMM-6637 Revert "Revert "PMM-6460 Pg stat monitor (#183)" (#184)"

### PR DESCRIPTION
**Pull request by JiriCtvrtka**
This reverts commit f25b6300eb8e93a29f5c60520ede84fc6b6c73c4.

### CODE REVIEW

**Comment by JiriCtvrtka** [comment]
I take a look on:
https://github.com/percona/pmm/pull/579
https://github.com/percona/qan-api2/pull/97

And both looks like already prepared, so after approve this PR I will merge all 3 PR's into 2.11 branch right? Thanks.

**Comment by AlekSi** [comment]
Is it the same as https://github.com/percona/pmm-agent/pull/186 ?

**Comment by JiriCtvrtka** [comment]
@AlekSi 186 was created from this branch and 186 should also contains changes for 6567.

**Comment by BupycHuk** [comment]
@AlekSi looks like they are not same. At least based on the lines changed. @JiriCtvrtka could you close incorrect one?

**Comment by JiriCtvrtka** [comment]
@BupycHuk @AlekSi Then it it this one. https://github.com/percona/pmm-agent/pull/186 contains these changes and changes for 6567. So will close it.

**Comment by JiriCtvrtka** [comment]
Then only:

https://github.com/percona/pmm/pull/579
https://github.com/percona/qan-api2/pull/97

Should be reviewed. I convert them to ready for review.

**Pull request closed without merging**
