### PR TITLE
SAAS-140 Skip timestamp fields for now.

### PR DESCRIPTION
**Pull request by AlekSi**
Tests fail with MariaDB 10.4.13 due to bug in their image: https://jira.mariadb.org/browse/MDEV-22542

### CODE REVIEW

**Comment by BupycHuk** [comment]
@AlekSi travis CI is failed

**Comment by AlekSi** [comment]
@BupycHuk Please check description

**Comment by BupycHuk** [comment]
Can we skip it for MariaDB 10.4.13?

**Comment by AlekSi** [comment]
We can, but we should not: we track changes in third-party software with our tests too. I expect them to fix their Docker image soon. If not, we will reconsider.

**Comment by BupycHuk** [comment]
ok, let's merge then

**Comment by AlekSi** [comment]
Except that I can't merge it now. Working on restoring our access…

**Pull request merged**
