### PR TITLE
PMM-7326 add logging level

### PR DESCRIPTION
**Pull request by YaroslavPodorvanov**
PMM-7326

Build: SUBMODULES-2385

- [github.com/percona/pmm-admin PMM-7326](https://github.com/percona/pmm-admin/pull/182)

### CODE REVIEW

**Comment by ritbl** [comment]
@YaroslavPodorvanov thanks for the PR
in the ticket we have following requrement:
- `log-level passed by pmm-admin inherited by all exporters and components`

Can you please confirm that it gets propagated and you have tested it. Can you pls add a couple of unit tests?

**Comment by ritbl** [comment]
sorry, closed by an accident

**Comment by YaroslavPodorvanov** [comment]
> @YaroslavPodorvanov thanks for the PR in the ticket we have following requrement:
> 
> * `log-level passed by pmm-admin inherited by all exporters and components`
> 
> Can you please confirm that it gets propagated and you have tested it. Can you pls add a couple of unit tests?

@ritbl yes, i will add to *pmm-admin* to cover https://github.com/percona/pmm-admin/pull/182/files#diff-a3e558392e7eb7daafd5fa9b30a7d1721647243b2e0f85e37abdb92394db194cR91

**Comment by YaroslavPodorvanov** [comment]
Add unit test for `pmm-admin` https://github.com/percona/pmm-admin/pull/182/commits/3f6e2eb091e0834af13afd47ba6ad0b496cbb00d#diff-143d43e64779b8e9c50cf2edf03c56858bf34dfd6bf376e3d8b54a202bddd20aR97

**Comment by ritbl** [comment]
@YaroslavPodorvanov have you tested that arg is propagated to exporters?

**Comment by YaroslavPodorvanov** [comment]
> @YaroslavPodorvanov have you tested that arg is propagated to exporters?
Yes

**Comment by YaroslavPodorvanov** [comment]
Exporter research

| exporter                                                          | owner                                              | logger                           | comment                                                                      | used       | pmm-agent |
|-------------------------------------------------------------------|----------------------------------------------------|----------------------------------|------------------------------------------------------------------------------|------------|-----------|
| [node_exporter](https://github.com/percona/node_exporter)         | forked from prometheus/node_exporter               | github.com/prometheus/common/log | exists CLI flag "log.level" inside github.com/prometheus/common/log.AddFlags | ✔ AddFlags | ❌         |
| [mysqld_exporter](https://github.com/percona/mysqld_exporter)     | forked from prometheus/mysqld_exporter             | github.com/prometheus/common/log | exists CLI flag "log.level" inside github.com/prometheus/common/log.AddFlags | ❌          | ❌         |
| [rds_exporter](https://github.com/percona/rds_exporter)           | forked from Technofy/cloudwatch_exporter           | github.com/prometheus/common/log | exists CLI flag "log.level" inside github.com/prometheus/common/log.AddFlags | ✔ AddFlags | ❌         |
| [postgres_exporter](https://github.com/percona/postgres_exporter) | forked from prometheus-community/postgres_exporter | github.com/prometheus/common/log | exists CLI flag "log.level" inside github.com/prometheus/common/log.AddFlags | ✔ AddFlags | ❌         |
| [mongodb_exporter](https://github.com/percona/mongodb_exporter)   | percona                                            | github.com/sirupsen/logrus       | exists CLI flag "log.level" and logrus.New().SetLevel(...)                   | ✔ SetLevel️ | ❌         |
| [proxysql_exporter](https://github.com/percona/proxysql_exporter) | percona                                            | github.com/prometheus/common/log | exists CLI flag "log.level" inside github.com/prometheus/common/log.AddFlags | ❌ AddFlags | ❌         |

**Comment by YaroslavPodorvanov** [comment]
move to https://github.com/percona/pmm-agent/pull/346

**Pull request closed without merging**
